# Virtualization Physical Hosts - independent of any specific DC design
---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: VirtualizationPhysicalHost
  data:
    - name: "fra1-pve-01"
      description: "Proxmox VE host in Frankfurt"
      object_template: VIRTUALIZATION_HOST
      location: "fra-1"
      platform: [Generic, Linux]
      status: active
      vcpus: 64
      memory: 512
      disk: 4000
      member_of_groups:
        - virtualization_hosts

    - name: "fra1-pve-02"
      description: "Proxmox VE host in Frankfurt"
      object_template: VIRTUALIZATION_HOST
      location: "fra-1"
      platform: [Generic, Linux]
      status: active
      vcpus: 64
      memory: 512
      disk: 4000
      member_of_groups:
        - virtualization_hosts

    - name: "fra1-kvm-01"
      description: "KVM host in Frankfurt"
      object_template: VIRTUALIZATION_HOST
      location: "fra-1"
      platform: [Generic, Linux]
      status: active
      vcpus: 32
      memory: 256
      disk: 2000
      member_of_groups:
        - virtualization_hosts

    - name: "fra1-kvm-02"
      description: "KVM host in Frankfurt"
      object_template: VIRTUALIZATION_HOST
      location: "fra-1"
      platform: [Generic, Linux]
      status: active
      vcpus: 32
      memory: 256
      disk: 2000
      member_of_groups:
        - virtualization_hosts

    - name: "fra1-esx-01"
      description: "VMware ESXi host in Frankfurt"
      object_template: VIRTUALIZATION_HOST
      location: "fra-1"
      platform: [Generic, Linux]
      status: active
      vcpus: 48
      memory: 384
      disk: 3000
      member_of_groups:
        - virtualization_hosts

    - name: "fra1-hv-01"
      description: "Microsoft Hyper-V host in Frankfurt"
      object_template: VIRTUALIZATION_HOST
      location: "fra-1"
      platform: [Generic, Windows]
      status: active
      vcpus: 48
      memory: 384
      disk: 3000
      member_of_groups:
        - virtualization_hosts
