# Virtualization Clusters - independent of any specific DC design
---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: VirtualizationCluster
  data:
    - name: "FRA1-PROXMOX-CLUSTER"
      description: "Proxmox VE cluster in Frankfurt"
      cluster_type: proxmox
      hosts:
        - fra1-pve-01
        - fra1-pve-02

    - name: "FRA1-KVM-CLUSTER"
      description: "KVM cluster in Frankfurt"
      cluster_type: kvm
      hosts:
        - fra1-kvm-01
        - fra1-kvm-02
