query topology_cables($name: String!) {
  TopologyDataCenter(name__value: $name) {
    edges {
      node {
        devices {
          edges {
            node {
              name {
                value
              }
              interfaces {
                edges {
                  node {
                    name {
                      value
                    }
                    ... on InterfacePhysical {
                      connector {
                        node {
                          hfid
                          display_label
                          ... on DcimCable {
                            status {
                              value
                            }
                            cable_type {
                              value
                            }
                            color {
                              value
                            }
                            label {
                              value
                            }
                            length {
                              value
                            }
                          }
                          connected_endpoints {
                            edges {
                              node {
                                __typename
                                ... on InterfacePhysical {
                                  name {
                                    value
                                  }
                                  device {
                                    node {
                                      name {
                                        value
                                      }
                                    }
                                  }
                                }
                                ... on DcimConsoleInterface {
                                  name {
                                    value
                                  }
                                  device {
                                    node {
                                      name {
                                        value
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                    ... on DcimConsoleInterface {
                      connector {
                        node {
                          hfid
                          display_label
                          ... on DcimCable {
                            status {
                              value
                            }
                            cable_type {
                              value
                            }
                            color {
                              value
                            }
                            label {
                              value
                            }
                            length {
                              value
                            }
                          }
                          connected_endpoints {
                            edges {
                              node {
                                __typename
                                ... on InterfacePhysical {
                                  name {
                                    value
                                  }
                                  device {
                                    node {
                                      name {
                                        value
                                      }
                                    }
                                  }
                                }
                                ... on DcimConsoleInterface {
                                  name {
                                    value
                                  }
                                  device {
                                    node {
                                      name {
                                        value
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
