query topology_info($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        name {
          value
        }
        management_subnet {
          node{
            prefix{
              value
            }
          }
        }
        design {
          node {
            type {
              value
            }
          }
        }
        devices {
          edges {
            node {
              name {
                value
              }
              os_version {
                value
              }
              primary_address {
                node {
                  address {
                    value
                  }
                }
              }
              platform {
                node {
                  name {
                    value
                  }
                  containerlab_os {
                    value
                  }
                }
              }
              ... on DcimDevice {
                role {
                  value
                }
                device_type {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
              ... on DcimVirtualDevice {
                role {
                  value
                }
                device_type {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
              interfaces {
                edges {
                  node {
                    name {
                      value
                    }
                    role {
                      value
                    }
                    ... on InterfacePhysical {
                      connector {
                        node {
                          hfid
                          display_label
                          ... on DcimCable {
                            status {
                              value
                            }
                            cable_type {
                              value
                            }
                          }
                          connected_endpoints {
                            edges {
                              node {
                                __typename
                                ... on InterfacePhysical {
                                  name {
                                    value
                                  }
                                  role {
                                    value
                                  }
                                  device {
                                    node {
                                      name {
                                        value
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
