#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        Boolean,
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPHostOptional,
        String,
        StringOptional,
        URLOptional,
    )


class DcimConnector(CoreNode):
    connected_endpoints: RelationshipManager


class TopologyDeployment(CoreNode):
    description: StringOptional
    emulation: Boolean
    name: String
    customer_subnet: RelatedNode
    design: RelatedNode
    devices: RelationshipManager
    location: RelatedNode
    management_subnet: RelatedNode


class DcimEndpoint(CoreNode):
    connector: RelatedNode


class LocationGeneric(CoreNode):
    description: StringOptional
    name: String
    shortname: String
    tags: RelationshipManager


class OrganizationGeneric(CoreNode):
    description: StringOptional
    name: String
    tags: RelationshipManager


class ServiceGeneric(CoreNode):
    name: String
    status: Dropdown
    owner: RelatedNode


class DcimGenericDevice(CoreNode):
    description: StringOptional
    name: String
    os_version: StringOptional
    interfaces: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    tags: RelationshipManager


class ServiceGenericDevice(CoreNode):
    device: RelatedNode


class ServiceGenericInterfaces(CoreNode):
    interfaces: RelationshipManager


class DcimGenericSFP(CoreNode):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: Dropdown
    interface: RelatedNode
    manufacturer: RelatedNode
    spare_location: RelatedNode


class ComputeGenericUnit(CoreNode):
    disk: IntegerOptional
    memory: IntegerOptional
    vcpus: IntegerOptional


class InterfaceHasSubInterface(CoreNode):
    sub_interfaces: RelationshipManager


class VirtualizationHostVirtualMachine(CoreNode):
    name: String
    virtual_machines: RelationshipManager


class LocationHosting(CoreNode):
    shortname: String
    devices: RelationshipManager
    prefixes: RelationshipManager


class DcimInterface(CoreNode):
    description: StringOptional
    mtu: Integer
    name: String
    role: DropdownOptional
    status: Dropdown
    device: RelatedNode
    tags: RelationshipManager


class InterfaceLayer2(CoreNode):
    l2_mode: DropdownOptional


class InterfaceLayer3(CoreNode):
    dot1q_id: IntegerOptional
    mac_address: StringOptional
    ip_addresses: RelationshipManager


class NetworkManagementServer(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    ip_addresses: RelationshipManager
    location: RelationshipManager


class ServicePeering(CoreNode):
    peering_type: Dropdown
    session_scope: Dropdown


class DcimPhysicalDevice(CoreNode):
    position: IntegerOptional
    rack_face: Dropdown
    serial: StringOptional
    device_type: RelatedNode
    location: RelatedNode


class RoutingPolicy(CoreNode):
    address_family: Dropdown
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional


class RoutingProtocol(CoreNode):
    description: String
    status: Dropdown
    device: RelatedNode


class CloudResource(CoreNode):
    cloud_id: StringOptional
    description: StringOptional
    name: String
    status: Dropdown
    tags: RelationshipManager


class ServiceRouting(CoreNode):
    name: String


class CloudAccount(CoreNode):
    account_id: String
    description: StringOptional
    environment: DropdownOptional
    name: String
    status: Dropdown
    owner: RelatedNode
    provider: RelatedNode
    tags: RelationshipManager


class SecurityAddressGroup(CoreNode):
    description: StringOptional
    name: String
    fqdns: RelationshipManager
    ip_addresses: RelationshipManager
    ip_ranges: RelationshipManager
    prefixes: RelationshipManager


class RoutingAggregateRoute(RoutingProtocol):
    discard: BooleanOptional
    export_policies: StringOptional
    import_policies: StringOptional
    destination: RelationshipManager


class SecurityApplication(CoreNode):
    category: StringOptional
    default_ports: StringOptional
    description: StringOptional
    name: String
    risk_level: IntegerOptional
    subcategory: StringOptional


class RoutingAutonomousSystem(CoreNode):
    asn: Integer
    description: StringOptional
    name: String
    location: RelatedNode
    owner: RelatedNode


class CloudAvailabilityZone(CoreNode):
    name: String
    zone_code: String
    region: RelatedNode


class ServiceBGP(ServiceGeneric, ServiceGenericDevice, ServiceGenericInterfaces, ServiceRouting):
    graceful_restart: BooleanOptional
    multipath: BooleanOptional
    session_type: Dropdown
    local_as: RelatedNode
    local_ip: RelatedNode
    peer_group: RelatedNode
    remote_as: RelatedNode
    remote_ip: RelatedNode
    router_id: RelatedNode


class RoutingBGPCommunity(CoreNode):
    community: String
    description: StringOptional
    name: String
    routing_policy: RelationshipManager
    tags: RelationshipManager


class RoutingBGPPeerGroup(CoreNode):
    bfd_enabled: BooleanOptional
    description: String
    ebgp_multihop: IntegerOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    name: String
    password: StringOptional
    peer_group_type: DropdownOptional
    route_reflector_client: BooleanOptional
    send_community: BooleanOptional
    send_community_extended: BooleanOptional


class ServiceBGPPeering(ServiceGeneric, ServicePeering):
    bfd_enabled: BooleanOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    med: IntegerOptional
    password: StringOptional
    remove_private_as: BooleanOptional
    send_community: BooleanOptional
    send_extended_community: BooleanOptional
    session_type: Dropdown
    ttl_security: IntegerOptional
    deployment: RelatedNode


class RoutingBGPRRCluster(CoreNode):
    description: StringOptional
    name: String
    cluster_id: RelatedNode
    peer_groups: RelationshipManager


class DcimBidiSFP(DcimGenericSFP):
    wavelength_rx: Integer
    wavelength_tx: Integer


class TopologyBranchOffice(CoreArtifactTarget, TopologyDeployment):
    owner: RelatedNode


class LocationBuilding(LocationGeneric, LocationHosting):
    facility_id: StringOptional
    is_cloud: Boolean
    physical_address: StringOptional
    owner: RelatedNode


class DcimCable(DcimConnector):
    cable_type: DropdownOptional
    color: DropdownOptional
    label: StringOptional
    length: IntegerOptional
    status: DropdownOptional


class VirtualizationCluster(CoreNode):
    cluster_type: DropdownOptional
    description: StringOptional
    name: String
    hosts: RelationshipManager
    virtual_machines: RelationshipManager


class TopologyColocationCenter(CoreArtifactTarget, TopologyDeployment):
    provider: RelatedNode
    public_subnet: RelatedNode
    technical_subnet: RelatedNode


class DcimConsoleInterface(DcimInterface, DcimEndpoint, CoreArtifactTarget):
    port: Integer
    speed: Integer


class LocationCountry(LocationGeneric):
    timezone: StringOptional


class OrganizationCustomer(OrganizationGeneric):
    customer_id: StringOptional
    ip_prefixes: RelationshipManager
    namespaces: RelationshipManager


class TopologyDataCenter(CoreArtifactTarget, TopologyDeployment):
    strategy: Dropdown
    provider: RelatedNode
    public_subnet: RelatedNode
    technical_subnet: RelatedNode


class DcimDevice(CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice):
    role: DropdownOptional


class DcimDeviceType(CoreNode):
    description: StringOptional
    full_depth: Boolean
    height: Integer
    name: String
    part_number: StringOptional
    weight: IntegerOptional
    manufacturer: RelatedNode
    platform: RelatedNode
    tags: RelationshipManager


class NetworkDhcpOption(CoreNode):
    content: String
    description: StringOptional
    name: String
    option_code: Integer


class NetworkDhcpServer(NetworkManagementServer):
    lease_time: String
    dhcp_options: RelationshipManager


class DocsDocs(CoreNode):
    link: URLOptional
    name: String


class CloudElasticIP(CloudResource):
    name: String
    public_ip: IPHost
    account: RelatedNode
    instance: RelatedNode
    network_interface: RelatedNode
    region: RelatedNode


class DesignElement(CoreNode):
    description: StringOptional
    name: String
    quantity: Integer
    role: DropdownOptional
    device_type: RelatedNode
    template: RelatedNode


class SecurityFQDN(CoreNode):
    description: StringOptional
    fqdn: String
    name: String


class SecurityFirewall(CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice):
    role: DropdownOptional
    status: Dropdown
    policies: RelationshipManager


class LoadbalancerHealthCheck(CoreNode):
    check: Dropdown
    description: String
    fall: IntegerOptional
    rise: IntegerOptional
    timeout: IntegerOptional


class IpamIPAddress(BuiltinIPAddress):
    fqdn: StringOptional


class SecurityIPAddress(CoreNode):
    description: StringOptional
    name: String
    ipam_ip_address: RelatedNode


class SecurityIPRange(CoreNode):
    description: StringOptional
    end: String
    name: String
    start: String


class CloudInstance(CloudResource):
    cpu_count: IntegerOptional
    instance_type: StringOptional
    memory_gb: IntegerOptional
    name: String
    os_type: DropdownOptional
    private_ip: IPHostOptional
    public_ip: IPHostOptional
    root_volume_size_gb: IntegerOptional
    account: RelatedNode
    network_interfaces: RelationshipManager
    security_groups: RelationshipManager
    subnet: RelatedNode
    zone: RelatedNode


class CloudInternetGateway(CloudResource):
    name: String
    account: RelatedNode
    virtual_network: RelatedNode


class IpamL2Domain(CoreNode):
    name: String
    vlans: RelationshipManager


class OrganizationManufacturer(CoreNode):
    description: StringOptional
    name: String
    device_type: RelationshipManager
    platform: RelationshipManager


class LocationMetro(LocationGeneric):
    pass


class CloudNATGateway(CloudResource):
    name: String
    public_ip: IPHostOptional
    account: RelatedNode
    subnet: RelatedNode


class NetworkNTPServer(NetworkManagementServer):
    pass


class NetworkNameServer(NetworkManagementServer):
    pass


class CloudNetworkInterface(CloudResource):
    is_primary: Boolean
    mac_address: StringOptional
    name: String
    private_ip: IPHostOptional
    public_ip: IPHostOptional
    instance: RelatedNode
    ip_addresses: RelationshipManager
    security_groups: RelationshipManager
    subnet: RelatedNode


class ServiceNetworkSegment(ServiceGeneric, ServiceGenericInterfaces):
    customer_name: String
    environment: Dropdown
    external_routing: BooleanOptional
    name: String
    segment_type: Dropdown
    tenant_isolation: Dropdown
    vlan_id: Integer
    deployment: RelatedNode
    prefix: RelatedNode


class ServiceOSPF(ServiceGeneric, ServiceGenericDevice, ServiceGenericInterfaces, ServiceRouting):
    process_id: String
    reference_bandwidth: IntegerOptional
    router_type: Dropdown
    version: Dropdown
    area: RelatedNode
    ospf_interface_profile: RelatedNode
    router_id: RelatedNode


class RoutingOSPFArea(CoreNode):
    area: Integer
    area_type: Dropdown
    description: StringOptional
    name: String


class RoutingOSPFInterface(CoreNode):
    authentication_key: StringOptional
    authentication_mode: DropdownOptional
    metric: IntegerOptional
    mode: Dropdown
    name: String


class ServiceOSPFPeering(ServiceGeneric, ServicePeering):
    area_type: Dropdown
    authentication_key: StringOptional
    authentication_type: DropdownOptional
    cost: IntegerOptional
    dead_interval: IntegerOptional
    hello_interval: IntegerOptional
    network_type: Dropdown
    priority: IntegerOptional
    retransmit_interval: IntegerOptional
    deployment: RelatedNode


class ServicePIM(ServiceGeneric, ServiceGenericDevice, ServiceGenericInterfaces, ServiceRouting):
    dr_priority: IntegerOptional
    rp_mode: DropdownOptional
    pim_interface_profile: RelationshipManager
    rp_address: RelatedNode


class RoutingPIMInterface(CoreNode):
    dr_priority: IntegerOptional
    hello_interval: IntegerOptional
    name: String
    pim_mode: Dropdown


class InterfacePhysical(DcimInterface, InterfaceLayer2, InterfaceLayer3, DcimEndpoint, InterfaceHasSubInterface):
    pass


class VirtualizationPhysicalHost(
    CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice, ComputeGenericUnit, VirtualizationHostVirtualMachine
):
    cluster: RelatedNode


class DcimPlatform(CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    name: String
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    devices: RelationshipManager
    manufacturer: RelatedNode


class LocationPod(LocationGeneric):
    pass


class SecurityPolicy(CoreNode):
    description: StringOptional
    name: String
    firewalls: RelationshipManager
    rules: RelationshipManager


class RoutingPolicyAggregate(RoutingPolicy):
    pass


class RoutingPolicyBGP(RoutingPolicy):
    pass


class RoutingPolicyOSPF(RoutingPolicy):
    pass


class RoutingPolicyPIM(RoutingPolicy):
    pass


class SecurityPolicyRule(CoreNode):
    action: Dropdown
    index: Integer
    log: BooleanOptional
    name: String
    applications: RelationshipManager
    destination_addresses: RelationshipManager
    destination_zone: RelatedNode
    policy: RelatedNode
    schedule: RelatedNode
    security_profile: RelatedNode
    services: RelationshipManager
    source_addresses: RelationshipManager
    source_zone: RelatedNode
    url_categories: RelationshipManager


class IpamPrefix(BuiltinIPPrefix):
    role: DropdownOptional
    status: Dropdown
    gateway: RelatedNode
    location: RelatedNode
    organization: RelatedNode


class SecurityPrefix(CoreNode):
    description: StringOptional
    name: String
    ipam_prefix: RelatedNode


class OrganizationProvider(OrganizationGeneric):
    pass


class CloudProvider(CoreNode):
    console_url: URLOptional
    name: String
    provider_type: Dropdown
    accounts: RelationshipManager
    organization: RelatedNode


class LocationRack(LocationGeneric, LocationHosting, CoreArtifactTarget):
    facility_id: StringOptional
    height: Integer
    owner: RelatedNode


class CloudRegion(CoreNode):
    geographic_location: StringOptional
    name: String
    region_code: String
    availability_zones: RelationshipManager
    provider: RelatedNode


class LocationRegion(LocationGeneric):
    pass


class CloudRouteTable(CloudResource):
    is_main: Boolean
    name: String
    subnets: RelationshipManager
    virtual_network: RelatedNode


class LocationRow(LocationGeneric):
    facility_id: StringOptional
    owner: RelatedNode


class SecuritySchedule(CoreNode):
    days_of_week: String
    description: StringOptional
    end_time: String
    name: String
    start_time: String
    timezone: StringOptional


class CloudSecurityGroup(CloudResource):
    name: String
    account: RelatedNode
    virtual_network: RelatedNode


class SecuritySecurityProfile(CoreNode):
    antivirus_enabled: BooleanOptional
    description: StringOptional
    ips_enabled: BooleanOptional
    name: String
    url_filtering_enabled: BooleanOptional


class SecuritySegmentACLRule(CoreNode):
    action: Dropdown
    description: StringOptional
    direction: Dropdown
    index: Integer
    log: BooleanOptional
    name: String
    acl: RelatedNode
    destination_addresses: RelationshipManager
    services: RelationshipManager
    source_addresses: RelationshipManager


class SecuritySegmentAccessControlList(CoreNode):
    acl_type: Dropdown
    description: StringOptional
    name: String


class SecuritySegmentSecurityProfile(CoreNode):
    default_action: Dropdown
    description: StringOptional
    enable_arp_inspection: BooleanOptional
    enable_dhcp_snooping: BooleanOptional
    enable_micro_segmentation: BooleanOptional
    max_mac_addresses: IntegerOptional
    name: String


class SecuritySegmentSecurityZone(CoreNode):
    description: StringOptional
    isolation_level: DropdownOptional
    name: String
    trust_level: Integer


class LoadbalancerServer(CoreNode):
    description: StringOptional
    hostname: String
    status: Dropdown
    ip_address: RelatedNode
    virtual_ips: RelationshipManager


class SecurityService(CoreNode):
    description: StringOptional
    name: String
    port: Integer
    protocol: Dropdown


class SecurityServiceGroup(CoreNode):
    description: StringOptional
    name: String
    service_ranges: RelationshipManager
    services: RelationshipManager


class SecurityServiceRange(CoreNode):
    description: StringOptional
    end: Integer
    name: String
    protocol: Dropdown
    start: Integer


class DcimStandardSFP(DcimGenericSFP):
    pass


class CloudSubnet(CloudResource):
    auto_assign_public_ip: Boolean
    name: String
    subnet_type: Dropdown
    availability_zone: RelatedNode
    cidr_block: RelatedNode
    tags: RelationshipManager
    virtual_network: RelatedNode


class DesignTopology(CoreArtifactTarget):
    description: StringOptional
    name: String
    type: DropdownOptional
    elements: RelationshipManager


class SecurityURLCategory(CoreNode):
    description: StringOptional
    name: String
    risk_level: DropdownOptional


class ServiceVIP(ServiceGeneric, ServiceGenericDevice):
    balance: Dropdown
    description: String
    hostname: String
    mode: Dropdown
    name: String
    ssl_certificate: StringOptional
    backend_servers: RelationshipManager
    frontend_servers: RelationshipManager
    health_checks: RelationshipManager
    vip_ip: RelatedNode


class IpamVLAN(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    vlan_id: Integer
    l2domain: RelatedNode
    location: RelationshipManager
    prefixes: RelationshipManager


class InterfaceVirtual(DcimInterface, InterfaceLayer2, InterfaceLayer3):
    parent_interface: RelatedNode


class DcimVirtualDevice(CoreArtifactTarget, DcimGenericDevice):
    cpu: IntegerOptional
    memory: IntegerOptional
    role: DropdownOptional
    storage: IntegerOptional
    device_type: RelatedNode
    hosting_device: RelatedNode


class ServiceVirtualFabric(CoreNode):
    deployment_size: Dropdown
    name: String
    status: Dropdown
    customer: RelatedNode
    deployment: RelatedNode


class VirtualizationVirtualMachine(CoreArtifactTarget, DcimGenericDevice, ComputeGenericUnit):
    vmid: IntegerOptional
    cluster: RelatedNode
    customer: RelatedNode
    host: RelatedNode


class CloudVirtualNetwork(CloudResource):
    dns_hostnames: Boolean
    dns_support: Boolean
    is_default: Boolean
    name: String
    account: RelatedNode
    cidr_blocks: RelationshipManager
    region: RelatedNode
    subnets: RelationshipManager


class SecurityZone(CoreNode):
    description: StringOptional
    name: String
    trust_level: Integer
