---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: CoreGeneratorAction
  data:
    - name: dc
      description: Data Center
      generator: create_dc
    - name: pop
      description: Point of Presence
      generator: create_pop
    - name: segment
      description: Network Segment VxLAN VPN
      generator: create_segment
    - name: virtualization_host_cabling
      description: Cable a Virtualization Physical Host to leaf switches
      generator: cable_virtualization_host
